//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionCitasMedicas.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CITAS
    {
        public int id { get; set; }
        public int id_doctor { get; set; }
        [Required(ErrorMessage = "La especialidad es Requerida")]
        public int id_paciente { get; set; }

        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> id_horario { get; set; }
        public Nullable<System.TimeSpan> horaInicio { get; set; }
        public Nullable<System.TimeSpan> horaFinal { get; set; }
    
        public virtual DOCTOR DOCTOR { get; set; }
        public virtual HORARIO HORARIO { get; set; }
        public virtual PACIENTE PACIENTE { get; set; }
    }
}
