//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionCitasMedicas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS
    {
        public int id { get; set; }
        public string gmail { get; set; }
        public string contraseña { get; set; }
        public Nullable<int> id_rol { get; set; }
    
        public virtual ROL ROL { get; set; }
    }
}
